// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/dataEngine.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DataEngine {
  public static partial class DataEngine
  {
    static readonly string __ServiceName = "dataEngine.DataEngine";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataEngine.Plate_info> __Marshaller_dataEngine_Plate_info = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataEngine.Plate_info.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataEngine.Plate_info, global::DataEngine.Plate_info> __Method_Data_Plate_get = new grpc::Method<global::DataEngine.Plate_info, global::DataEngine.Plate_info>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Data_Plate_get",
        __Marshaller_dataEngine_Plate_info,
        __Marshaller_dataEngine_Plate_info);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataEngine.Plate_info, global::DataEngine.Plate_info> __Method_Data_Plate_set = new grpc::Method<global::DataEngine.Plate_info, global::DataEngine.Plate_info>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Data_Plate_set",
        __Marshaller_dataEngine_Plate_info,
        __Marshaller_dataEngine_Plate_info);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DataEngine.DataEngineReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DataEngine</summary>
    [grpc::BindServiceMethod(typeof(DataEngine), "BindService")]
    public abstract partial class DataEngineBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataEngine.Plate_info> Data_Plate_get(global::DataEngine.Plate_info request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataEngine.Plate_info> Data_Plate_set(global::DataEngine.Plate_info request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for DataEngine</summary>
    public partial class DataEngineClient : grpc::ClientBase<DataEngineClient>
    {
      /// <summary>Creates a new client for DataEngine</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataEngineClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for DataEngine that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public DataEngineClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataEngineClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected DataEngineClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DataEngine.Plate_info Data_Plate_get(global::DataEngine.Plate_info request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Data_Plate_get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DataEngine.Plate_info Data_Plate_get(global::DataEngine.Plate_info request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Data_Plate_get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DataEngine.Plate_info> Data_Plate_getAsync(global::DataEngine.Plate_info request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Data_Plate_getAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DataEngine.Plate_info> Data_Plate_getAsync(global::DataEngine.Plate_info request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Data_Plate_get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DataEngine.Plate_info Data_Plate_set(global::DataEngine.Plate_info request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Data_Plate_set(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::DataEngine.Plate_info Data_Plate_set(global::DataEngine.Plate_info request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Data_Plate_set, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DataEngine.Plate_info> Data_Plate_setAsync(global::DataEngine.Plate_info request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Data_Plate_setAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::DataEngine.Plate_info> Data_Plate_setAsync(global::DataEngine.Plate_info request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Data_Plate_set, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override DataEngineClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DataEngineClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DataEngineBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Data_Plate_get, serviceImpl.Data_Plate_get)
          .AddMethod(__Method_Data_Plate_set, serviceImpl.Data_Plate_set).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DataEngineBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Data_Plate_get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataEngine.Plate_info, global::DataEngine.Plate_info>(serviceImpl.Data_Plate_get));
      serviceBinder.AddMethod(__Method_Data_Plate_set, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataEngine.Plate_info, global::DataEngine.Plate_info>(serviceImpl.Data_Plate_set));
    }

  }
}
#endregion
