// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/pipetteModule.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PipetteModule {
  public static partial class PipetteModule
  {
    static readonly string __ServiceName = "pipetteModule.PipetteModule";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::PipetteModule.Pipe_action_param> __Marshaller_pipetteModule_Pipe_action_param = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PipetteModule.Pipe_action_param.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::PipetteModule.Pipe_result> __Marshaller_pipetteModule_Pipe_result = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PipetteModule.Pipe_result.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::PipetteModule.Pipe_cali_param> __Marshaller_pipetteModule_Pipe_cali_param = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PipetteModule.Pipe_cali_param.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result> __Method_Pipe_reset = new grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_reset",
        __Marshaller_pipetteModule_Pipe_action_param,
        __Marshaller_pipetteModule_Pipe_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result> __Method_Pipe_breakTip = new grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_breakTip",
        __Marshaller_pipetteModule_Pipe_action_param,
        __Marshaller_pipetteModule_Pipe_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result> __Method_Pipe_aspirate = new grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_aspirate",
        __Marshaller_pipetteModule_Pipe_action_param,
        __Marshaller_pipetteModule_Pipe_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result> __Method_Pipe_disense = new grpc::Method<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_disense",
        __Marshaller_pipetteModule_Pipe_action_param,
        __Marshaller_pipetteModule_Pipe_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param> __Method_Pipe_get_cali = new grpc::Method<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_get_cali",
        __Marshaller_pipetteModule_Pipe_cali_param,
        __Marshaller_pipetteModule_Pipe_cali_param);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param> __Method_Pipe_set_cali = new grpc::Method<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pipe_set_cali",
        __Marshaller_pipetteModule_Pipe_cali_param,
        __Marshaller_pipetteModule_Pipe_cali_param);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PipetteModule.PipetteModuleReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PipetteModule</summary>
    [grpc::BindServiceMethod(typeof(PipetteModule), "BindService")]
    public abstract partial class PipetteModuleBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_result> Pipe_reset(global::PipetteModule.Pipe_action_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_result> Pipe_breakTip(global::PipetteModule.Pipe_action_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_result> Pipe_aspirate(global::PipetteModule.Pipe_action_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_result> Pipe_disense(global::PipetteModule.Pipe_action_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_cali_param> Pipe_get_cali(global::PipetteModule.Pipe_cali_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::PipetteModule.Pipe_cali_param> Pipe_set_cali(global::PipetteModule.Pipe_cali_param request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PipetteModule</summary>
    public partial class PipetteModuleClient : grpc::ClientBase<PipetteModuleClient>
    {
      /// <summary>Creates a new client for PipetteModule</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PipetteModuleClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PipetteModule that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PipetteModuleClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PipetteModuleClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PipetteModuleClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_reset(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_reset(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_reset(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_reset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_resetAsync(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_resetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_resetAsync(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_reset, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_breakTip(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_breakTip(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_breakTip(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_breakTip, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_breakTipAsync(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_breakTipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_breakTipAsync(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_breakTip, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_aspirate(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_aspirate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_aspirate(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_aspirate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_aspirateAsync(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_aspirateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_aspirateAsync(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_aspirate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_disense(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_disense(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_result Pipe_disense(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_disense, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_disenseAsync(global::PipetteModule.Pipe_action_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_disenseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_result> Pipe_disenseAsync(global::PipetteModule.Pipe_action_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_disense, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_cali_param Pipe_get_cali(global::PipetteModule.Pipe_cali_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_get_cali(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_cali_param Pipe_get_cali(global::PipetteModule.Pipe_cali_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_get_cali, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_cali_param> Pipe_get_caliAsync(global::PipetteModule.Pipe_cali_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_get_caliAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_cali_param> Pipe_get_caliAsync(global::PipetteModule.Pipe_cali_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_get_cali, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_cali_param Pipe_set_cali(global::PipetteModule.Pipe_cali_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_set_cali(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::PipetteModule.Pipe_cali_param Pipe_set_cali(global::PipetteModule.Pipe_cali_param request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pipe_set_cali, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_cali_param> Pipe_set_caliAsync(global::PipetteModule.Pipe_cali_param request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pipe_set_caliAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::PipetteModule.Pipe_cali_param> Pipe_set_caliAsync(global::PipetteModule.Pipe_cali_param request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pipe_set_cali, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PipetteModuleClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PipetteModuleClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PipetteModuleBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Pipe_reset, serviceImpl.Pipe_reset)
          .AddMethod(__Method_Pipe_breakTip, serviceImpl.Pipe_breakTip)
          .AddMethod(__Method_Pipe_aspirate, serviceImpl.Pipe_aspirate)
          .AddMethod(__Method_Pipe_disense, serviceImpl.Pipe_disense)
          .AddMethod(__Method_Pipe_get_cali, serviceImpl.Pipe_get_cali)
          .AddMethod(__Method_Pipe_set_cali, serviceImpl.Pipe_set_cali).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PipetteModuleBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Pipe_reset, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(serviceImpl.Pipe_reset));
      serviceBinder.AddMethod(__Method_Pipe_breakTip, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(serviceImpl.Pipe_breakTip));
      serviceBinder.AddMethod(__Method_Pipe_aspirate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(serviceImpl.Pipe_aspirate));
      serviceBinder.AddMethod(__Method_Pipe_disense, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_action_param, global::PipetteModule.Pipe_result>(serviceImpl.Pipe_disense));
      serviceBinder.AddMethod(__Method_Pipe_get_cali, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param>(serviceImpl.Pipe_get_cali));
      serviceBinder.AddMethod(__Method_Pipe_set_cali, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipetteModule.Pipe_cali_param, global::PipetteModule.Pipe_cali_param>(serviceImpl.Pipe_set_cali));
    }

  }
}
#endregion
