// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/qybotrun.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QybotrunPkg {

  /// <summary>Holder for reflection information generated from proto/qybotrun.proto</summary>
  public static partial class QybotrunReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/qybotrun.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QybotrunReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwcm90by9xeWJvdHJ1bi5wcm90bxIMcXlib3RydW5fcGtnGhtnb29nbGUv",
            "cHJvdG9idWYvZW1wdHkucHJvdG8i7QIKDHJ1bnRpbWVfaW5mbxIzCglzeXNf",
            "c3RhdGUYASABKA4yIC5xeWJvdHJ1bl9wa2cucnVudGltZV9pbmZvLnN0YXRl",
            "Eg8KB2RldGFpbHMYAiABKAkSEgoKdG90YWxfc3RlcBgDIAEoBRIUCgxjdXJy",
            "ZW50X3N0ZXAYBCABKAUSEQoJc3RlcF9uYW1lGAUgASgJEhMKC3NjcmlwdF9u",
            "YW1lGAYgASgJEhYKDmJyZWFrcG9pbnRfbXNnGAcgASgJEhcKD2JyZWFrcG9p",
            "bnRfbGluZRgIIAEoBRIUCgx3YWl0X3RpbWVfbXMYCSABKAUifgoFc3RhdGUS",
            "DgoKc3RhdGVfaWRsZRAAEg0KCXN0YXRlX2VychABEg4KCnN0YXRlX2J1c3kQ",
            "AhIPCgtzdGF0ZV9wYXVzZRADEg8KC3N0YXRlX2lucHV0EAQSFAoQc3RhdGVf",
            "YnJlYWtwb2ludBAFEg4KCnN0YXRlX3dhaXQQBiIaCgpkZWJ1Z19kYXRhEgwK",
            "BGRhdGEYASABKAkiQQoLc2NyaXB0X2RhdGESDAoEZGF0YRgBIAEoCRISCgpz",
            "dGFydF9zdGVwGAIgASgFEhAKCGlzX2RlYnVnGAMgASgFIoIBCg5leGVjdXRl",
            "X3Jlc3VsdBI0CgZyZXN1bHQYASABKA4yJC5xeWJvdHJ1bl9wa2cuZXhlY3V0",
            "ZV9yZXN1bHQuZXJyY29kZRIPCgdlcnJpbmZvGAIgASgJIikKB2VycmNvZGUS",
            "CwoHc3VjY2VlZBAAEggKBGJ1c3kQARIHCgNlcnIQAiIaCgppbnB1dF9kYXRh",
            "EgwKBGRhdGEYASABKAkyvQQKCHF5Ym90cnVuEkEKC2dldF9ydW50aW1lEhYu",
            "Z29vZ2xlLnByb3RvYnVmLkVtcHR5GhoucXlib3RydW5fcGtnLnJ1bnRpbWVf",
            "aW5mbxJFCgpzY3JpcHRfcnVuEhkucXlib3RydW5fcGtnLnNjcmlwdF9kYXRh",
            "GhwucXlib3RydW5fcGtnLmV4ZWN1dGVfcmVzdWx0EkQKDHNjcmlwdF9wYXVz",
            "ZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRocLnF5Ym90cnVuX3BrZy5leGVj",
            "dXRlX3Jlc3VsdBJFCg1zY3JpcHRfcmVzdW1lEhYuZ29vZ2xlLnByb3RvYnVm",
            "LkVtcHR5GhwucXlib3RydW5fcGtnLmV4ZWN1dGVfcmVzdWx0EkQKDHNjcmlw",
            "dF9hYm9ydBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRocLnF5Ym90cnVuX3Br",
            "Zy5leGVjdXRlX3Jlc3VsdBJCCgxzY3JpcHRfZGVidWcSGC5xeWJvdHJ1bl9w",
            "a2cuZGVidWdfZGF0YRoYLnF5Ym90cnVuX3BrZy5kZWJ1Z19kYXRhEkoKEHNj",
            "cmlwdF9zZXRfaW5wdXQSGC5xeWJvdHJ1bl9wa2cuaW5wdXRfZGF0YRocLnF5",
            "Ym90cnVuX3BrZy5leGVjdXRlX3Jlc3VsdBJEChBzY3JpcHRfZ2V0X2lucHV0",
            "EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GhgucXlib3RydW5fcGtnLmlucHV0",
            "X2RhdGFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QybotrunPkg.runtime_info), global::QybotrunPkg.runtime_info.Parser, new[]{ "SysState", "Details", "TotalStep", "CurrentStep", "StepName", "ScriptName", "BreakpointMsg", "BreakpointLine", "WaitTimeMs" }, null, new[]{ typeof(global::QybotrunPkg.runtime_info.Types.state) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QybotrunPkg.debug_data), global::QybotrunPkg.debug_data.Parser, new[]{ "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QybotrunPkg.script_data), global::QybotrunPkg.script_data.Parser, new[]{ "Data", "StartStep", "IsDebug" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QybotrunPkg.execute_result), global::QybotrunPkg.execute_result.Parser, new[]{ "Result", "Errinfo" }, null, new[]{ typeof(global::QybotrunPkg.execute_result.Types.errcode) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QybotrunPkg.input_data), global::QybotrunPkg.input_data.Parser, new[]{ "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class runtime_info : pb::IMessage<runtime_info>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<runtime_info> _parser = new pb::MessageParser<runtime_info>(() => new runtime_info());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<runtime_info> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QybotrunPkg.QybotrunReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public runtime_info() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public runtime_info(runtime_info other) : this() {
      sysState_ = other.sysState_;
      details_ = other.details_;
      totalStep_ = other.totalStep_;
      currentStep_ = other.currentStep_;
      stepName_ = other.stepName_;
      scriptName_ = other.scriptName_;
      breakpointMsg_ = other.breakpointMsg_;
      breakpointLine_ = other.breakpointLine_;
      waitTimeMs_ = other.waitTimeMs_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public runtime_info Clone() {
      return new runtime_info(this);
    }

    /// <summary>Field number for the "sys_state" field.</summary>
    public const int SysStateFieldNumber = 1;
    private global::QybotrunPkg.runtime_info.Types.state sysState_ = global::QybotrunPkg.runtime_info.Types.state.Idle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::QybotrunPkg.runtime_info.Types.state SysState {
      get { return sysState_; }
      set {
        sysState_ = value;
      }
    }

    /// <summary>Field number for the "details" field.</summary>
    public const int DetailsFieldNumber = 2;
    private string details_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Details {
      get { return details_; }
      set {
        details_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "total_step" field.</summary>
    public const int TotalStepFieldNumber = 3;
    private int totalStep_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalStep {
      get { return totalStep_; }
      set {
        totalStep_ = value;
      }
    }

    /// <summary>Field number for the "current_step" field.</summary>
    public const int CurrentStepFieldNumber = 4;
    private int currentStep_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CurrentStep {
      get { return currentStep_; }
      set {
        currentStep_ = value;
      }
    }

    /// <summary>Field number for the "step_name" field.</summary>
    public const int StepNameFieldNumber = 5;
    private string stepName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StepName {
      get { return stepName_; }
      set {
        stepName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "script_name" field.</summary>
    public const int ScriptNameFieldNumber = 6;
    private string scriptName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScriptName {
      get { return scriptName_; }
      set {
        scriptName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "breakpoint_msg" field.</summary>
    public const int BreakpointMsgFieldNumber = 7;
    private string breakpointMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BreakpointMsg {
      get { return breakpointMsg_; }
      set {
        breakpointMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "breakpoint_line" field.</summary>
    public const int BreakpointLineFieldNumber = 8;
    private int breakpointLine_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BreakpointLine {
      get { return breakpointLine_; }
      set {
        breakpointLine_ = value;
      }
    }

    /// <summary>Field number for the "wait_time_ms" field.</summary>
    public const int WaitTimeMsFieldNumber = 9;
    private int waitTimeMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WaitTimeMs {
      get { return waitTimeMs_; }
      set {
        waitTimeMs_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as runtime_info);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(runtime_info other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SysState != other.SysState) return false;
      if (Details != other.Details) return false;
      if (TotalStep != other.TotalStep) return false;
      if (CurrentStep != other.CurrentStep) return false;
      if (StepName != other.StepName) return false;
      if (ScriptName != other.ScriptName) return false;
      if (BreakpointMsg != other.BreakpointMsg) return false;
      if (BreakpointLine != other.BreakpointLine) return false;
      if (WaitTimeMs != other.WaitTimeMs) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SysState != global::QybotrunPkg.runtime_info.Types.state.Idle) hash ^= SysState.GetHashCode();
      if (Details.Length != 0) hash ^= Details.GetHashCode();
      if (TotalStep != 0) hash ^= TotalStep.GetHashCode();
      if (CurrentStep != 0) hash ^= CurrentStep.GetHashCode();
      if (StepName.Length != 0) hash ^= StepName.GetHashCode();
      if (ScriptName.Length != 0) hash ^= ScriptName.GetHashCode();
      if (BreakpointMsg.Length != 0) hash ^= BreakpointMsg.GetHashCode();
      if (BreakpointLine != 0) hash ^= BreakpointLine.GetHashCode();
      if (WaitTimeMs != 0) hash ^= WaitTimeMs.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SysState != global::QybotrunPkg.runtime_info.Types.state.Idle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SysState);
      }
      if (Details.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Details);
      }
      if (TotalStep != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalStep);
      }
      if (CurrentStep != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CurrentStep);
      }
      if (StepName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StepName);
      }
      if (ScriptName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ScriptName);
      }
      if (BreakpointMsg.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BreakpointMsg);
      }
      if (BreakpointLine != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(BreakpointLine);
      }
      if (WaitTimeMs != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(WaitTimeMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SysState != global::QybotrunPkg.runtime_info.Types.state.Idle) {
        output.WriteRawTag(8);
        output.WriteEnum((int) SysState);
      }
      if (Details.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Details);
      }
      if (TotalStep != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalStep);
      }
      if (CurrentStep != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CurrentStep);
      }
      if (StepName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(StepName);
      }
      if (ScriptName.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ScriptName);
      }
      if (BreakpointMsg.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BreakpointMsg);
      }
      if (BreakpointLine != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(BreakpointLine);
      }
      if (WaitTimeMs != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(WaitTimeMs);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SysState != global::QybotrunPkg.runtime_info.Types.state.Idle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SysState);
      }
      if (Details.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Details);
      }
      if (TotalStep != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalStep);
      }
      if (CurrentStep != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentStep);
      }
      if (StepName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StepName);
      }
      if (ScriptName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScriptName);
      }
      if (BreakpointMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BreakpointMsg);
      }
      if (BreakpointLine != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BreakpointLine);
      }
      if (WaitTimeMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WaitTimeMs);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(runtime_info other) {
      if (other == null) {
        return;
      }
      if (other.SysState != global::QybotrunPkg.runtime_info.Types.state.Idle) {
        SysState = other.SysState;
      }
      if (other.Details.Length != 0) {
        Details = other.Details;
      }
      if (other.TotalStep != 0) {
        TotalStep = other.TotalStep;
      }
      if (other.CurrentStep != 0) {
        CurrentStep = other.CurrentStep;
      }
      if (other.StepName.Length != 0) {
        StepName = other.StepName;
      }
      if (other.ScriptName.Length != 0) {
        ScriptName = other.ScriptName;
      }
      if (other.BreakpointMsg.Length != 0) {
        BreakpointMsg = other.BreakpointMsg;
      }
      if (other.BreakpointLine != 0) {
        BreakpointLine = other.BreakpointLine;
      }
      if (other.WaitTimeMs != 0) {
        WaitTimeMs = other.WaitTimeMs;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SysState = (global::QybotrunPkg.runtime_info.Types.state) input.ReadEnum();
            break;
          }
          case 18: {
            Details = input.ReadString();
            break;
          }
          case 24: {
            TotalStep = input.ReadInt32();
            break;
          }
          case 32: {
            CurrentStep = input.ReadInt32();
            break;
          }
          case 42: {
            StepName = input.ReadString();
            break;
          }
          case 50: {
            ScriptName = input.ReadString();
            break;
          }
          case 58: {
            BreakpointMsg = input.ReadString();
            break;
          }
          case 64: {
            BreakpointLine = input.ReadInt32();
            break;
          }
          case 72: {
            WaitTimeMs = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SysState = (global::QybotrunPkg.runtime_info.Types.state) input.ReadEnum();
            break;
          }
          case 18: {
            Details = input.ReadString();
            break;
          }
          case 24: {
            TotalStep = input.ReadInt32();
            break;
          }
          case 32: {
            CurrentStep = input.ReadInt32();
            break;
          }
          case 42: {
            StepName = input.ReadString();
            break;
          }
          case 50: {
            ScriptName = input.ReadString();
            break;
          }
          case 58: {
            BreakpointMsg = input.ReadString();
            break;
          }
          case 64: {
            BreakpointLine = input.ReadInt32();
            break;
          }
          case 72: {
            WaitTimeMs = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the runtime_info message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum state {
        [pbr::OriginalName("state_idle")] Idle = 0,
        [pbr::OriginalName("state_err")] Err = 1,
        [pbr::OriginalName("state_busy")] Busy = 2,
        [pbr::OriginalName("state_pause")] Pause = 3,
        [pbr::OriginalName("state_input")] Input = 4,
        [pbr::OriginalName("state_breakpoint")] Breakpoint = 5,
        [pbr::OriginalName("state_wait")] Wait = 6,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class debug_data : pb::IMessage<debug_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<debug_data> _parser = new pb::MessageParser<debug_data>(() => new debug_data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<debug_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QybotrunPkg.QybotrunReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public debug_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public debug_data(debug_data other) : this() {
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public debug_data Clone() {
      return new debug_data(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as debug_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(debug_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(debug_data other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class script_data : pb::IMessage<script_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<script_data> _parser = new pb::MessageParser<script_data>(() => new script_data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<script_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QybotrunPkg.QybotrunReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public script_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public script_data(script_data other) : this() {
      data_ = other.data_;
      startStep_ = other.startStep_;
      isDebug_ = other.isDebug_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public script_data Clone() {
      return new script_data(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "start_step" field.</summary>
    public const int StartStepFieldNumber = 2;
    private int startStep_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int StartStep {
      get { return startStep_; }
      set {
        startStep_ = value;
      }
    }

    /// <summary>Field number for the "is_debug" field.</summary>
    public const int IsDebugFieldNumber = 3;
    private int isDebug_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IsDebug {
      get { return isDebug_; }
      set {
        isDebug_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as script_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(script_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      if (StartStep != other.StartStep) return false;
      if (IsDebug != other.IsDebug) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (StartStep != 0) hash ^= StartStep.GetHashCode();
      if (IsDebug != 0) hash ^= IsDebug.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (StartStep != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartStep);
      }
      if (IsDebug != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IsDebug);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (StartStep != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartStep);
      }
      if (IsDebug != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IsDebug);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (StartStep != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartStep);
      }
      if (IsDebug != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IsDebug);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(script_data other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.StartStep != 0) {
        StartStep = other.StartStep;
      }
      if (other.IsDebug != 0) {
        IsDebug = other.IsDebug;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
          case 16: {
            StartStep = input.ReadInt32();
            break;
          }
          case 24: {
            IsDebug = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
          case 16: {
            StartStep = input.ReadInt32();
            break;
          }
          case 24: {
            IsDebug = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class execute_result : pb::IMessage<execute_result>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<execute_result> _parser = new pb::MessageParser<execute_result>(() => new execute_result());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<execute_result> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QybotrunPkg.QybotrunReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public execute_result() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public execute_result(execute_result other) : this() {
      result_ = other.result_;
      errinfo_ = other.errinfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public execute_result Clone() {
      return new execute_result(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::QybotrunPkg.execute_result.Types.errcode result_ = global::QybotrunPkg.execute_result.Types.errcode.Succeed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::QybotrunPkg.execute_result.Types.errcode Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "errinfo" field.</summary>
    public const int ErrinfoFieldNumber = 2;
    private string errinfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Errinfo {
      get { return errinfo_; }
      set {
        errinfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as execute_result);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(execute_result other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Errinfo != other.Errinfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::QybotrunPkg.execute_result.Types.errcode.Succeed) hash ^= Result.GetHashCode();
      if (Errinfo.Length != 0) hash ^= Errinfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::QybotrunPkg.execute_result.Types.errcode.Succeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Errinfo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Errinfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::QybotrunPkg.execute_result.Types.errcode.Succeed) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Errinfo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Errinfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::QybotrunPkg.execute_result.Types.errcode.Succeed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Errinfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Errinfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(execute_result other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::QybotrunPkg.execute_result.Types.errcode.Succeed) {
        Result = other.Result;
      }
      if (other.Errinfo.Length != 0) {
        Errinfo = other.Errinfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::QybotrunPkg.execute_result.Types.errcode) input.ReadEnum();
            break;
          }
          case 18: {
            Errinfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::QybotrunPkg.execute_result.Types.errcode) input.ReadEnum();
            break;
          }
          case 18: {
            Errinfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the execute_result message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum errcode {
        [pbr::OriginalName("succeed")] Succeed = 0,
        [pbr::OriginalName("busy")] Busy = 1,
        [pbr::OriginalName("err")] Err = 2,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class input_data : pb::IMessage<input_data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<input_data> _parser = new pb::MessageParser<input_data>(() => new input_data());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<input_data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QybotrunPkg.QybotrunReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public input_data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public input_data(input_data other) : this() {
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public input_data Clone() {
      return new input_data(this);
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as input_data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(input_data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Data.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(input_data other) {
      if (other == null) {
        return;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
