// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/scriptEngine.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ScriptEngine {
  public static partial class ScriptEngine
  {
    static readonly string __ServiceName = "scriptEngine.ScriptEngine";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScriptEngine.Script_data> __Marshaller_scriptEngine_Script_data = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScriptEngine.Script_data.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScriptEngine.Script_result> __Marshaller_scriptEngine_Script_result = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScriptEngine.Script_result.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScriptEngine.Void> __Marshaller_scriptEngine_Void = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScriptEngine.Void.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ScriptEngine.Script_info> __Marshaller_scriptEngine_Script_info = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ScriptEngine.Script_info.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result> __Method_Script_check = new grpc::Method<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Script_check",
        __Marshaller_scriptEngine_Script_data,
        __Marshaller_scriptEngine_Script_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result> __Method_Script_run = new grpc::Method<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Script_run",
        __Marshaller_scriptEngine_Script_data,
        __Marshaller_scriptEngine_Script_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result> __Method_Script_pause = new grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Script_pause",
        __Marshaller_scriptEngine_Void,
        __Marshaller_scriptEngine_Script_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result> __Method_Script_continue = new grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Script_continue",
        __Marshaller_scriptEngine_Void,
        __Marshaller_scriptEngine_Script_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result> __Method_Script_stop = new grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Script_stop",
        __Marshaller_scriptEngine_Void,
        __Marshaller_scriptEngine_Script_result);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_info> __Method_Script_monitor = new grpc::Method<global::ScriptEngine.Void, global::ScriptEngine.Script_info>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Script_monitor",
        __Marshaller_scriptEngine_Void,
        __Marshaller_scriptEngine_Script_info);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ScriptEngine.ScriptEngineReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ScriptEngine</summary>
    [grpc::BindServiceMethod(typeof(ScriptEngine), "BindService")]
    public abstract partial class ScriptEngineBase
    {
      /// <summary>
      ///  检查脚本.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScriptEngine.Script_result> Script_check(global::ScriptEngine.Script_data request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  脚本运行.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScriptEngine.Script_result> Script_run(global::ScriptEngine.Script_data request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  脚本暂停 .
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScriptEngine.Script_result> Script_pause(global::ScriptEngine.Void request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  脚本继续.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScriptEngine.Script_result> Script_continue(global::ScriptEngine.Void request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  脚本停止.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ScriptEngine.Script_result> Script_stop(global::ScriptEngine.Void request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///  脚本状态监听.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task Script_monitor(global::ScriptEngine.Void request, grpc::IServerStreamWriter<global::ScriptEngine.Script_info> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ScriptEngine</summary>
    public partial class ScriptEngineClient : grpc::ClientBase<ScriptEngineClient>
    {
      /// <summary>Creates a new client for ScriptEngine</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ScriptEngineClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ScriptEngine that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ScriptEngineClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ScriptEngineClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ScriptEngineClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///  检查脚本.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_check(global::ScriptEngine.Script_data request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_check(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  检查脚本.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_check(global::ScriptEngine.Script_data request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Script_check, null, options, request);
      }
      /// <summary>
      ///  检查脚本.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_checkAsync(global::ScriptEngine.Script_data request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_checkAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  检查脚本.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_checkAsync(global::ScriptEngine.Script_data request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Script_check, null, options, request);
      }
      /// <summary>
      ///  脚本运行.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_run(global::ScriptEngine.Script_data request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_run(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本运行.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_run(global::ScriptEngine.Script_data request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Script_run, null, options, request);
      }
      /// <summary>
      ///  脚本运行.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_runAsync(global::ScriptEngine.Script_data request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_runAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本运行.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_runAsync(global::ScriptEngine.Script_data request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Script_run, null, options, request);
      }
      /// <summary>
      ///  脚本暂停 .
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_pause(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_pause(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本暂停 .
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_pause(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Script_pause, null, options, request);
      }
      /// <summary>
      ///  脚本暂停 .
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_pauseAsync(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_pauseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本暂停 .
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_pauseAsync(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Script_pause, null, options, request);
      }
      /// <summary>
      ///  脚本继续.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_continue(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_continue(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本继续.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_continue(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Script_continue, null, options, request);
      }
      /// <summary>
      ///  脚本继续.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_continueAsync(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_continueAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本继续.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_continueAsync(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Script_continue, null, options, request);
      }
      /// <summary>
      ///  脚本停止.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_stop(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_stop(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本停止.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::ScriptEngine.Script_result Script_stop(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Script_stop, null, options, request);
      }
      /// <summary>
      ///  脚本停止.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_stopAsync(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_stopAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本停止.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::ScriptEngine.Script_result> Script_stopAsync(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Script_stop, null, options, request);
      }
      /// <summary>
      ///  脚本状态监听.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScriptEngine.Script_info> Script_monitor(global::ScriptEngine.Void request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Script_monitor(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///  脚本状态监听.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::ScriptEngine.Script_info> Script_monitor(global::ScriptEngine.Void request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Script_monitor, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ScriptEngineClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ScriptEngineClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ScriptEngineBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Script_check, serviceImpl.Script_check)
          .AddMethod(__Method_Script_run, serviceImpl.Script_run)
          .AddMethod(__Method_Script_pause, serviceImpl.Script_pause)
          .AddMethod(__Method_Script_continue, serviceImpl.Script_continue)
          .AddMethod(__Method_Script_stop, serviceImpl.Script_stop)
          .AddMethod(__Method_Script_monitor, serviceImpl.Script_monitor).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ScriptEngineBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Script_check, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result>(serviceImpl.Script_check));
      serviceBinder.AddMethod(__Method_Script_run, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScriptEngine.Script_data, global::ScriptEngine.Script_result>(serviceImpl.Script_run));
      serviceBinder.AddMethod(__Method_Script_pause, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(serviceImpl.Script_pause));
      serviceBinder.AddMethod(__Method_Script_continue, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(serviceImpl.Script_continue));
      serviceBinder.AddMethod(__Method_Script_stop, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ScriptEngine.Void, global::ScriptEngine.Script_result>(serviceImpl.Script_stop));
      serviceBinder.AddMethod(__Method_Script_monitor, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::ScriptEngine.Void, global::ScriptEngine.Script_info>(serviceImpl.Script_monitor));
    }

  }
}
#endregion
