//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OctoFixFlow.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OctoFixFlow.Resource.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off the fill light 的本地化字符串。
        /// </summary>
        public static string DeviceLightClose {
            get {
                return ResourceManager.GetString("DeviceLightClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on the fill light 的本地化字符串。
        /// </summary>
        public static string DeviceLightOpen {
            get {
                return ResourceManager.GetString("DeviceLightOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation failed: 的本地化字符串。
        /// </summary>
        public static string DeviceOperationFailure {
            get {
                return ResourceManager.GetString("DeviceOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate successfully 的本地化字符串。
        /// </summary>
        public static string DeviceOperationSucc {
            get {
                return ResourceManager.GetString("DeviceOperationSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off the UV light 的本地化字符串。
        /// </summary>
        public static string DeviceUVClose {
            get {
                return ResourceManager.GetString("DeviceUVClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn on the UV light 的本地化字符串。
        /// </summary>
        public static string DeviceUVOpen {
            get {
                return ResourceManager.GetString("DeviceUVOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End 的本地化字符串。
        /// </summary>
        public static string FlowStepEnd {
            get {
                return ResourceManager.GetString("FlowStepEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string FlowStepStart {
            get {
                return ResourceManager.GetString("FlowStepStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steps 的本地化字符串。
        /// </summary>
        public static string FlowStepSteps {
            get {
                return ResourceManager.GetString("FlowStepSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for operation 的本地化字符串。
        /// </summary>
        public static string FlowStepWaitContent {
            get {
                return ResourceManager.GetString("FlowStepWaitContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device status loading failed: 的本地化字符串。
        /// </summary>
        public static string GrpcDeviceLoadFail {
            get {
                return ResourceManager.GetString("GrpcDeviceLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment status loading completed 的本地化字符串。
        /// </summary>
        public static string GrpcDeviceLoadSucc {
            get {
                return ResourceManager.GetString("GrpcDeviceLoadSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device door not closed 的本地化字符串。
        /// </summary>
        public static string GrpcFailDoor {
            get {
                return ResourceManager.GetString("GrpcFailDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Initializing... 的本地化字符串。
        /// </summary>
        public static string GrpcIniting {
            get {
                return ResourceManager.GetString("GrpcIniting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device begins initialization. 的本地化字符串。
        /// </summary>
        public static string GrpcInitStart {
            get {
                return ResourceManager.GetString("GrpcInitStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device reset successful 的本地化字符串。
        /// </summary>
        public static string GrpcInitSucc {
            get {
                return ResourceManager.GetString("GrpcInitSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP address loading failed 的本地化字符串。
        /// </summary>
        public static string GrpcIPFail {
            get {
                return ResourceManager.GetString("GrpcIPFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GRPC initialization failed: 的本地化字符串。
        /// </summary>
        public static string GrpcLoadFail {
            get {
                return ResourceManager.GetString("GrpcLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GRPC loading is successful 的本地化字符串。
        /// </summary>
        public static string GrpcLoadSucc {
            get {
                return ResourceManager.GetString("GrpcLoadSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start and end steps are non-deletable 的本地化字符串。
        /// </summary>
        public static string GrpcStartEndRemove {
            get {
                return ResourceManager.GetString("GrpcStartEndRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process has not stopped 的本地化字符串。
        /// </summary>
        public static string GrpcStartRunning {
            get {
                return ResourceManager.GetString("GrpcStartRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load fail 的本地化字符串。
        /// </summary>
        public static string MainWindowDetailLoadFail {
            get {
                return ResourceManager.GetString("MainWindowDetailLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logged in is: 的本地化字符串。
        /// </summary>
        public static string MainWindowDetailLoginIN {
            get {
                return ResourceManager.GetString("MainWindowDetailLoginIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password is empty 的本地化字符串。
        /// </summary>
        public static string MainWindowDetailPassEmpty {
            get {
                return ResourceManager.GetString("MainWindowDetailPassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STL file not found 的本地化字符串。
        /// </summary>
        public static string MainWindowDetailSTL {
            get {
                return ResourceManager.GetString("MainWindowDetailSTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username is empty 的本地化字符串。
        /// </summary>
        public static string MainWindowDetailUserEmpty {
            get {
                return ResourceManager.GetString("MainWindowDetailUserEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected file is empty 的本地化字符串。
        /// </summary>
        public static string OpenFileDialog_Empty {
            get {
                return ResourceManager.GetString("OpenFileDialog_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read the file 的本地化字符串。
        /// </summary>
        public static string OpenFileDialog_Error {
            get {
                return ResourceManager.GetString("OpenFileDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON Script Files (*.json)|*.json|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Script File to Load 的本地化字符串。
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select aspiration position 的本地化字符串。
        /// </summary>
        public static string QuickAisPos {
            get {
                return ResourceManager.GetString("QuickAisPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asp Pos: 的本地化字符串。
        /// </summary>
        public static string QuickAspPos {
            get {
                return ResourceManager.GetString("QuickAspPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column 的本地化字符串。
        /// </summary>
        public static string QuickColumn {
            get {
                return ResourceManager.GetString("QuickColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select dispensing position 的本地化字符串。
        /// </summary>
        public static string QuickDisPos {
            get {
                return ResourceManager.GetString("QuickDisPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disp Pos: 的本地化字符串。
        /// </summary>
        public static string QuickDispPos {
            get {
                return ResourceManager.GetString("QuickDispPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed?: 的本地化字符串。
        /// </summary>
        public static string QuickFixed {
            get {
                return ResourceManager.GetString("QuickFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string QuickGenerate {
            get {
                return ResourceManager.GetString("QuickGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liquid Selection: 的本地化字符串。
        /// </summary>
        public static string QuickLiquidSelection {
            get {
                return ResourceManager.GetString("QuickLiquidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mix Asp?: 的本地化字符串。
        /// </summary>
        public static string QuickMixAsp {
            get {
                return ResourceManager.GetString("QuickMixAsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Times: 的本地化字符串。
        /// </summary>
        public static string QuickMixAspTimes {
            get {
                return ResourceManager.GetString("QuickMixAspTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volue: 的本地化字符串。
        /// </summary>
        public static string QuickMixAspVol {
            get {
                return ResourceManager.GetString("QuickMixAspVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter sample count between 1-96 的本地化字符串。
        /// </summary>
        public static string QuickOne96Samples {
            get {
                return ResourceManager.GetString("QuickOne96Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rinse?: 的本地化字符串。
        /// </summary>
        public static string QuickRinse {
            get {
                return ResourceManager.GetString("QuickRinse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay: 的本地化字符串。
        /// </summary>
        public static string QuickRinseDelay {
            get {
                return ResourceManager.GetString("QuickRinseDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volue: 的本地化字符串。
        /// </summary>
        public static string QuickRinseVol {
            get {
                return ResourceManager.GetString("QuickRinseVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample Qty: 的本地化字符串。
        /// </summary>
        public static string QuickSampleQty {
            get {
                return ResourceManager.GetString("QuickSampleQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select liquid parameters 的本地化字符串。
        /// </summary>
        public static string QuickSelectLiquid {
            get {
                return ResourceManager.GetString("QuickSelectLiquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Change?: 的本地化字符串。
        /// </summary>
        public static string QuickTipChange {
            get {
                return ResourceManager.GetString("QuickTipChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Change Settings: 的本地化字符串。
        /// </summary>
        public static string QuickTipChangeSettings {
            get {
                return ResourceManager.GetString("QuickTipChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Eject Pos: 的本地化字符串。
        /// </summary>
        public static string QuickTipEjectPos {
            get {
                return ResourceManager.GetString("QuickTipEjectPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select tip ejection position 的本地化字符串。
        /// </summary>
        public static string QuickTipOffPos {
            get {
                return ResourceManager.GetString("QuickTipOffPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select tip pickup position 的本地化字符串。
        /// </summary>
        public static string QuickTipOnPos {
            get {
                return ResourceManager.GetString("QuickTipOnPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Pick Pos: 的本地化字符串。
        /// </summary>
        public static string QuickTipPickPos {
            get {
                return ResourceManager.GetString("QuickTipPickPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Generate Process 的本地化字符串。
        /// </summary>
        public static string QuickTitile {
            get {
                return ResourceManager.GetString("QuickTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter valid aspiration volume 的本地化字符串。
        /// </summary>
        public static string QuickValidAspirationVolume {
            get {
                return ResourceManager.GetString("QuickValidAspirationVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resume process 的本地化字符串。
        /// </summary>
        public static string ScriptContinue {
            get {
                return ResourceManager.GetString("ScriptContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script loading failed 的本地化字符串。
        /// </summary>
        public static string ScriptLoadFail {
            get {
                return ResourceManager.GetString("ScriptLoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script loading successful 的本地化字符串。
        /// </summary>
        public static string ScriptLoadSucc {
            get {
                return ResourceManager.GetString("ScriptLoadSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process not started 的本地化字符串。
        /// </summary>
        public static string ScriptNotStart {
            get {
                return ResourceManager.GetString("ScriptNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause process 的本地化字符串。
        /// </summary>
        public static string ScriptPause {
            get {
                return ResourceManager.GetString("ScriptPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check process failed 的本地化字符串。
        /// </summary>
        public static string ScriptStartCheckFail {
            get {
                return ResourceManager.GetString("ScriptStartCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create script failed 的本地化字符串。
        /// </summary>
        public static string ScriptStartCreateFail {
            get {
                return ResourceManager.GetString("ScriptStartCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creating process scripts... 的本地化字符串。
        /// </summary>
        public static string ScriptStartCreating {
            get {
                return ResourceManager.GetString("ScriptStartCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please add process steps before starting 的本地化字符串。
        /// </summary>
        public static string ScriptStartEmpty {
            get {
                return ResourceManager.GetString("ScriptStartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start process failed 的本地化字符串。
        /// </summary>
        public static string ScriptStartFail {
            get {
                return ResourceManager.GetString("ScriptStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Some steps lack liquid parameters 的本地化字符串。
        /// </summary>
        public static string ScriptStartLiquidEmpty {
            get {
                return ResourceManager.GetString("ScriptStartLiquidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process starting execution 的本地化字符串。
        /// </summary>
        public static string ScriptStartSucc {
            get {
                return ResourceManager.GetString("ScriptStartSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process successfully generated 的本地化字符串。
        /// </summary>
        public static string ScriptSuccCrea {
            get {
                return ResourceManager.GetString("ScriptSuccCrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string ScriptUILogError {
            get {
                return ResourceManager.GetString("ScriptUILogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        public static string ScriptUILogIdle {
            get {
                return ResourceManager.GetString("ScriptUILogIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string ScriptUILogPause {
            get {
                return ResourceManager.GetString("ScriptUILogPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string ScriptUILogRun {
            get {
                return ResourceManager.GetString("ScriptUILogRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown state 的本地化字符串。
        /// </summary>
        public static string ScriptUILogUnknown {
            get {
                return ResourceManager.GetString("ScriptUILogUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not running 的本地化字符串。
        /// </summary>
        public static string ScriptUINotRun {
            get {
                return ResourceManager.GetString("ScriptUINotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumable 2D Drawing 的本地化字符串。
        /// </summary>
        public static string SettingCons2D {
            get {
                return ResourceManager.GetString("SettingCons2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A1 Well X Dist. 的本地化字符串。
        /// </summary>
        public static string SettingConsA1XDistance {
            get {
                return ResourceManager.GetString("SettingConsA1XDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A1 Well Y Dist. 的本地化字符串。
        /// </summary>
        public static string SettingConsA1YDistance {
            get {
                return ResourceManager.GetString("SettingConsA1YDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string SettingConsAdd {
            get {
                return ResourceManager.GetString("SettingConsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string SettingConsbasicInfo {
            get {
                return ResourceManager.GetString("SettingConsbasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Spacing 的本地化字符串。
        /// </summary>
        public static string SettingConsColumnSpacing {
            get {
                return ResourceManager.GetString("SettingConsColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cone Max Rad 的本地化字符串。
        /// </summary>
        public static string SettingConsConeMaxRadius {
            get {
                return ResourceManager.GetString("SettingConsConeMaxRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cone Min Rad 的本地化字符串。
        /// </summary>
        public static string SettingConsConeMinRadius {
            get {
                return ResourceManager.GetString("SettingConsConeMinRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cube 的本地化字符串。
        /// </summary>
        public static string SettingConsCube {
            get {
                return ResourceManager.GetString("SettingConsCube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cylinder 的本地化字符串。
        /// </summary>
        public static string SettingConsCylinder {
            get {
                return ResourceManager.GetString("SettingConsCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string SettingConsDescription {
            get {
                return ResourceManager.GetString("SettingConsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumable Dimension (mm) 的本地化字符串。
        /// </summary>
        public static string SettingConsDimension {
            get {
                return ResourceManager.GetString("SettingConsDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gripper X 的本地化字符串。
        /// </summary>
        public static string SettingConsGripperX {
            get {
                return ResourceManager.GetString("SettingConsGripperX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gripper Y 的本地化字符串。
        /// </summary>
        public static string SettingConsGripperY {
            get {
                return ResourceManager.GetString("SettingConsGripperY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gripper Z 的本地化字符串。
        /// </summary>
        public static string SettingConsGripperZ {
            get {
                return ResourceManager.GetString("SettingConsGripperZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string SettingConsHeight {
            get {
                return ResourceManager.GetString("SettingConsHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In 的本地化字符串。
        /// </summary>
        public static string SettingConsIn {
            get {
                return ResourceManager.GetString("SettingConsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string SettingConsLength {
            get {
                return ResourceManager.GetString("SettingConsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Cap 的本地化字符串。
        /// </summary>
        public static string SettingConsMaxCap {
            get {
                return ResourceManager.GetString("SettingConsMaxCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Usable Cap 的本地化字符串。
        /// </summary>
        public static string SettingConsMaxUsableCap {
            get {
                return ResourceManager.GetString("SettingConsMaxUsableCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Usable Vol 的本地化字符串。
        /// </summary>
        public static string SettingConsMaxUsableVolume {
            get {
                return ResourceManager.GetString("SettingConsMaxUsableVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Well Cap 的本地化字符串。
        /// </summary>
        public static string SettingConsMaxWellCapacity {
            get {
                return ResourceManager.GetString("SettingConsMaxWellCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string SettingConsName {
            get {
                return ResourceManager.GetString("SettingConsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NE 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchNE {
            get {
                return ResourceManager.GetString("SettingConsNotchNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NW 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchNW {
            get {
                return ResourceManager.GetString("SettingConsNotchNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notch Position 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchPosition {
            get {
                return ResourceManager.GetString("SettingConsNotchPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SE 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchSE {
            get {
                return ResourceManager.GetString("SettingConsNotchSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notch Setting 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchSetting {
            get {
                return ResourceManager.GetString("SettingConsNotchSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SW 的本地化字符串。
        /// </summary>
        public static string SettingConsNotchSW {
            get {
                return ResourceManager.GetString("SettingConsNotchSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num of Columns 的本地化字符串。
        /// </summary>
        public static string SettingConsNumColumns {
            get {
                return ResourceManager.GetString("SettingConsNumColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num of Rows 的本地化字符串。
        /// </summary>
        public static string SettingConsNumRows {
            get {
                return ResourceManager.GetString("SettingConsNumRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Num of Wells 的本地化字符串。
        /// </summary>
        public static string SettingConsNumWells {
            get {
                return ResourceManager.GetString("SettingConsNumWells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset &amp; Gripper Pos (mm) 的本地化字符串。
        /// </summary>
        public static string SettingConsOffsetGripperPos {
            get {
                return ResourceManager.GetString("SettingConsOffsetGripperPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset X 的本地化字符串。
        /// </summary>
        public static string SettingConsOffsetX {
            get {
                return ResourceManager.GetString("SettingConsOffsetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset Y 的本地化字符串。
        /// </summary>
        public static string SettingConsOffsetY {
            get {
                return ResourceManager.GetString("SettingConsOffsetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out 的本地化字符串。
        /// </summary>
        public static string SettingConsOut {
            get {
                return ResourceManager.GetString("SettingConsOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipette Tip Params 的本地化字符串。
        /// </summary>
        public static string SettingConsPipetteTipParams {
            get {
                return ResourceManager.GetString("SettingConsPipetteTipParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string SettingConsRemove {
            get {
                return ResourceManager.GetString("SettingConsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Spacing 的本地化字符串。
        /// </summary>
        public static string SettingConsRowSpacing {
            get {
                return ResourceManager.GetString("SettingConsRowSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial Number 的本地化字符串。
        /// </summary>
        public static string SettingConsSerialNum {
            get {
                return ResourceManager.GetString("SettingConsSerialNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Cone Lgth 的本地化字符串。
        /// </summary>
        public static string SettingConsTipConeLgth {
            get {
                return ResourceManager.GetString("SettingConsTipConeLgth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Head Ht 的本地化字符串。
        /// </summary>
        public static string SettingConsTipHeadHt {
            get {
                return ResourceManager.GetString("SettingConsTipHeadHt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Press Dpth 的本地化字符串。
        /// </summary>
        public static string SettingConsTipMountPressDpth {
            get {
                return ResourceManager.GetString("SettingConsTipMountPressDpth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip Total Lgth 的本地化字符串。
        /// </summary>
        public static string SettingConsTipTotalLgth {
            get {
                return ResourceManager.GetString("SettingConsTipTotalLgth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumables Management 的本地化字符串。
        /// </summary>
        public static string SettingConsTitile {
            get {
                return ResourceManager.GetString("SettingConsTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Length 的本地化字符串。
        /// </summary>
        public static string SettingConsTopLength {
            get {
                return ResourceManager.GetString("SettingConsTopLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Radius 的本地化字符串。
        /// </summary>
        public static string SettingConsTopRadius {
            get {
                return ResourceManager.GetString("SettingConsTopRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Shape 的本地化字符串。
        /// </summary>
        public static string SettingConsTopShape {
            get {
                return ResourceManager.GetString("SettingConsTopShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top Width 的本地化字符串。
        /// </summary>
        public static string SettingConsTopWidth {
            get {
                return ResourceManager.GetString("SettingConsTopWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string SettingConsType {
            get {
                return ResourceManager.GetString("SettingConsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microplate 的本地化字符串。
        /// </summary>
        public static string SettingConsTypeMicroplate {
            get {
                return ResourceManager.GetString("SettingConsTypeMicroplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string SettingConsTypeOther {
            get {
                return ResourceManager.GetString("SettingConsTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reservoir 的本地化字符串。
        /// </summary>
        public static string SettingConsTypeReservoir {
            get {
                return ResourceManager.GetString("SettingConsTypeReservoir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TipBox 的本地化字符串。
        /// </summary>
        public static string SettingConsTypeTipBox {
            get {
                return ResourceManager.GetString("SettingConsTypeTipBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Well Dpth (mm) 的本地化字符串。
        /// </summary>
        public static string SettingConsWellDepth {
            get {
                return ResourceManager.GetString("SettingConsWellDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Well Spec 的本地化字符串。
        /// </summary>
        public static string SettingConsWellSpec {
            get {
                return ResourceManager.GetString("SettingConsWellSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string SettingConsWidth {
            get {
                return ResourceManager.GetString("SettingConsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data has been updated. 的本地化字符串。
        /// </summary>
        public static string SettingDataSave {
            get {
                return ResourceManager.GetString("SettingDataSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string SettingLiquidAdd {
            get {
                return ResourceManager.GetString("SettingLiquidAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asp Delay 的本地化字符串。
        /// </summary>
        public static string SettingLiquidAspDelay {
            get {
                return ResourceManager.GetString("SettingLiquidAspDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Params 的本地化字符串。
        /// </summary>
        public static string SettingLiquidAspirationParams {
            get {
                return ResourceManager.GetString("SettingLiquidAspirationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asp Speed 的本地化字符串。
        /// </summary>
        public static string SettingLiquidAspSpeed {
            get {
                return ResourceManager.GetString("SettingLiquidAspSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Information 的本地化字符串。
        /// </summary>
        public static string SettingLiquidbasicInfo {
            get {
                return ResourceManager.GetString("SettingLiquidbasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string SettingLiquidDescription {
            get {
                return ResourceManager.GetString("SettingLiquidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disp Delay 的本地化字符串。
        /// </summary>
        public static string SettingLiquidDispDelay {
            get {
                return ResourceManager.GetString("SettingLiquidDispDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Params 的本地化字符串。
        /// </summary>
        public static string SettingLiquidDispensingParams {
            get {
                return ResourceManager.GetString("SettingLiquidDispensingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disp Speed 的本地化字符串。
        /// </summary>
        public static string SettingLiquidDispSpeed {
            get {
                return ResourceManager.GetString("SettingLiquidDispSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dist to Well Bot 的本地化字符串。
        /// </summary>
        public static string SettingLiquidDisttoWellBot {
            get {
                return ResourceManager.GetString("SettingLiquidDisttoWellBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In 的本地化字符串。
        /// </summary>
        public static string SettingLiquidIn {
            get {
                return ResourceManager.GetString("SettingLiquidIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string SettingLiquidName {
            get {
                return ResourceManager.GetString("SettingLiquidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Out 的本地化字符串。
        /// </summary>
        public static string SettingLiquidOut {
            get {
                return ResourceManager.GetString("SettingLiquidOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post-Asp Air 的本地化字符串。
        /// </summary>
        public static string SettingLiquidPostAspAir {
            get {
                return ResourceManager.GetString("SettingLiquidPostAspAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post-Disp Air 的本地化字符串。
        /// </summary>
        public static string SettingLiquidPostDispAir {
            get {
                return ResourceManager.GetString("SettingLiquidPostDispAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Asp Air 的本地化字符串。
        /// </summary>
        public static string SettingLiquidPreAspAir {
            get {
                return ResourceManager.GetString("SettingLiquidPreAspAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-Disp Air 的本地化字符串。
        /// </summary>
        public static string SettingLiquidPreDispAir {
            get {
                return ResourceManager.GetString("SettingLiquidPreDispAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string SettingLiquidRemove {
            get {
                return ResourceManager.GetString("SettingLiquidRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspirate 的本地化字符串。
        /// </summary>
        public static string SettingManualAspirate {
            get {
                return ResourceManager.GetString("SettingManualAspirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Params: 的本地化字符串。
        /// </summary>
        public static string SettingManualAspirationParams {
            get {
                return ResourceManager.GetString("SettingManualAspirationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backlash 的本地化字符串。
        /// </summary>
        public static string SettingManualBacklash {
            get {
                return ResourceManager.GetString("SettingManualBacklash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calibration Gear: 的本地化字符串。
        /// </summary>
        public static string SettingManualCalibrationGear {
            get {
                return ResourceManager.GetString("SettingManualCalibrationGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string SettingManualClose {
            get {
                return ResourceManager.GetString("SettingManualClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Control Center 的本地化字符串。
        /// </summary>
        public static string SettingManualControlCenter {
            get {
                return ResourceManager.GetString("SettingManualControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coord Fine Adj (mm): 的本地化字符串。
        /// </summary>
        public static string SettingManualCoordinateFineAdjustment {
            get {
                return ResourceManager.GetString("SettingManualCoordinateFineAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Plate Coordinates (mm): 的本地化字符串。
        /// </summary>
        public static string SettingManualCurrentPlateCoordinates {
            get {
                return ResourceManager.GetString("SettingManualCurrentPlateCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispense 的本地化字符串。
        /// </summary>
        public static string SettingManualDispense {
            get {
                return ResourceManager.GetString("SettingManualDispense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Params: 的本地化字符串。
        /// </summary>
        public static string SettingManualDispensingParams {
            get {
                return ResourceManager.GetString("SettingManualDispensingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eject Tip 的本地化字符串。
        /// </summary>
        public static string SettingManualEjectTip {
            get {
                return ResourceManager.GetString("SettingManualEjectTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Calib 的本地化字符串。
        /// </summary>
        public static string SettingManualGetCalibration {
            get {
                return ResourceManager.GetString("SettingManualGetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Plate 的本地化字符串。
        /// </summary>
        public static string SettingManualMovetoPlatePosition {
            get {
                return ResourceManager.GetString("SettingManualMovetoPlatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Z-axis 的本地化字符串。
        /// </summary>
        public static string SettingManualMoveZaxis {
            get {
                return ResourceManager.GetString("SettingManualMoveZaxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipette Control 的本地化字符串。
        /// </summary>
        public static string SettingManualPipetteControl {
            get {
                return ResourceManager.GetString("SettingManualPipetteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plate Position Calibration (XYZ) 的本地化字符串。
        /// </summary>
        public static string SettingManualPlatePositionCalibration {
            get {
                return ResourceManager.GetString("SettingManualPlatePositionCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string SettingManualReset {
            get {
                return ResourceManager.GetString("SettingManualReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset X 的本地化字符串。
        /// </summary>
        public static string SettingManualResetX {
            get {
                return ResourceManager.GetString("SettingManualResetX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Y 的本地化字符串。
        /// </summary>
        public static string SettingManualResetY {
            get {
                return ResourceManager.GetString("SettingManualResetY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Z 的本地化字符串。
        /// </summary>
        public static string SettingManualResetZ {
            get {
                return ResourceManager.GetString("SettingManualResetZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Coords 的本地化字符串。
        /// </summary>
        public static string SettingManualSaveCoordinates {
            get {
                return ResourceManager.GetString("SettingManualSaveCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Plate Position: 的本地化字符串。
        /// </summary>
        public static string SettingManualSelectPlatePosition {
            get {
                return ResourceManager.GetString("SettingManualSelectPlatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Calib 的本地化字符串。
        /// </summary>
        public static string SettingManualSetCalibration {
            get {
                return ResourceManager.GetString("SettingManualSetCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed (μl/s): 的本地化字符串。
        /// </summary>
        public static string SettingManualSpeed {
            get {
                return ResourceManager.GetString("SettingManualSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Control 的本地化字符串。
        /// </summary>
        public static string SettingManualTitile {
            get {
                return ResourceManager.GetString("SettingManualTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume (μl): 的本地化字符串。
        /// </summary>
        public static string SettingManualVolume {
            get {
                return ResourceManager.GetString("SettingManualVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Coordinate: 的本地化字符串。
        /// </summary>
        public static string SettingManualXCoordinate {
            get {
                return ResourceManager.GetString("SettingManualXCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Direction 的本地化字符串。
        /// </summary>
        public static string SettingManualXDirection {
            get {
                return ResourceManager.GetString("SettingManualXDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y Coordinate: 的本地化字符串。
        /// </summary>
        public static string SettingManualYCoordinate {
            get {
                return ResourceManager.GetString("SettingManualYCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y Direction 的本地化字符串。
        /// </summary>
        public static string SettingManualYDirection {
            get {
                return ResourceManager.GetString("SettingManualYDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z Coordinate: 的本地化字符串。
        /// </summary>
        public static string SettingManualZCoordinate {
            get {
                return ResourceManager.GetString("SettingManualZCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z Direction 的本地化字符串。
        /// </summary>
        public static string SettingManualZDirection {
            get {
                return ResourceManager.GetString("SettingManualZDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pipetting Parameters 的本地化字符串。
        /// </summary>
        public static string SettingPipeTitile {
            get {
                return ResourceManager.GetString("SettingPipeTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration Management 的本地化字符串。
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plate pos name not empty 的本地化字符串。
        /// </summary>
        public static string SQLPosNameNotEmpty {
            get {
                return ResourceManager.GetString("SQLPosNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air After Aspiration: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspAirA {
            get {
                return ResourceManager.GetString("StepDetailAspAirA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Before Aspiration: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspAirB {
            get {
                return ResourceManager.GetString("StepDetailAspAirB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Delay: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspDelay {
            get {
                return ResourceManager.GetString("StepDetailAspDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only supports microplates or reservoirs 的本地化字符串。
        /// </summary>
        public static string StepDetailAspDispConsTip {
            get {
                return ResourceManager.GetString("StepDetailAspDispConsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Distance: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspDist {
            get {
                return ResourceManager.GetString("StepDetailAspDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Parameters: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspirationParams {
            get {
                return ResourceManager.GetString("StepDetailAspirationParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspiration Speed: 的本地化字符串。
        /// </summary>
        public static string StepDetailAspSpeed {
            get {
                return ResourceManager.GetString("StepDetailAspSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Current: {0}) 的本地化字符串。
        /// </summary>
        public static string StepDetailCurrentCons {
            get {
                return ResourceManager.GetString("StepDetailCurrentCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string StepDetailDetails {
            get {
                return ResourceManager.GetString("StepDetailDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air After Dispensing: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispAirA {
            get {
                return ResourceManager.GetString("StepDetailDispAirA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Before Dispensing: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispAirB {
            get {
                return ResourceManager.GetString("StepDetailDispAirB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Delay: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispDelay {
            get {
                return ResourceManager.GetString("StepDetailDispDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Distance: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispDist {
            get {
                return ResourceManager.GetString("StepDetailDispDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Parameters: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispensingParams {
            get {
                return ResourceManager.GetString("StepDetailDispensingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispensing Speed: 的本地化字符串。
        /// </summary>
        public static string StepDetailDispSpeed {
            get {
                return ResourceManager.GetString("StepDetailDispSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Mixing 的本地化字符串。
        /// </summary>
        public static string StepDetailEnableMix {
            get {
                return ResourceManager.GetString("StepDetailEnableMix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial Delay(ms): 的本地化字符串。
        /// </summary>
        public static string StepDetailInitialDelay {
            get {
                return ResourceManager.GetString("StepDetailInitialDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initial Volume(ul): 的本地化字符串。
        /// </summary>
        public static string StepDetailInitialVol {
            get {
                return ResourceManager.GetString("StepDetailInitialVol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Liquid parameters: 的本地化字符串。
        /// </summary>
        public static string StepDetailLiquidParams {
            get {
                return ResourceManager.GetString("StepDetailLiquidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixing Times: 的本地化字符串。
        /// </summary>
        public static string StepDetailMixCount {
            get {
                return ResourceManager.GetString("StepDetailMixCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixed settings: 的本地化字符串。
        /// </summary>
        public static string StepDetailMixedSettings {
            get {
                return ResourceManager.GetString("StepDetailMixedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixing Volume(ul): 的本地化字符串。
        /// </summary>
        public static string StepDetailMixVolume {
            get {
                return ResourceManager.GetString("StepDetailMixVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Position: 的本地化字符串。
        /// </summary>
        public static string StepDetailOperationPosition {
            get {
                return ResourceManager.GetString("StepDetailOperationPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only supports tip boxes or waste bins 的本地化字符串。
        /// </summary>
        public static string StepDetailTipOnOffConsTip {
            get {
                return ResourceManager.GetString("StepDetailTipOnOffConsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume(ul): 的本地化字符串。
        /// </summary>
        public static string StepDetailVolume {
            get {
                return ResourceManager.GetString("StepDetailVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting Description: 的本地化字符串。
        /// </summary>
        public static string StepDetailWaitDesc {
            get {
                return ResourceManager.GetString("StepDetailWaitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note: Waiting time will be auto-converted to milliseconds. 的本地化字符串。
        /// </summary>
        public static string StepDetailWaitNote {
            get {
                return ResourceManager.GetString("StepDetailWaitNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting Time (seconds): 的本地化字符串。
        /// </summary>
        public static string StepDetailWaitTime {
            get {
                return ResourceManager.GetString("StepDetailWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Well Position Selection: 的本地化字符串。
        /// </summary>
        public static string StepDetailWellPosition {
            get {
                return ResourceManager.GetString("StepDetailWellPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Well Position Selection Area: 的本地化字符串。
        /// </summary>
        public static string StepDetailWellSelectionArea {
            get {
                return ResourceManager.GetString("StepDetailWellSelectionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aspirate 的本地化字符串。
        /// </summary>
        public static string WindowActionAspirate {
            get {
                return ResourceManager.GetString("WindowActionAspirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dispense 的本地化字符串。
        /// </summary>
        public static string WindowActionDispense {
            get {
                return ResourceManager.GetString("WindowActionDispense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Function Area 的本地化字符串。
        /// </summary>
        public static string WindowActionFunctionArea {
            get {
                return ResourceManager.GetString("WindowActionFunctionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Init 的本地化字符串。
        /// </summary>
        public static string WindowActionInit {
            get {
                return ResourceManager.GetString("WindowActionInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string WindowActionLight {
            get {
                return ResourceManager.GetString("WindowActionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load 的本地化字符串。
        /// </summary>
        public static string WindowActionLoad {
            get {
                return ResourceManager.GetString("WindowActionLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string WindowActionPause {
            get {
                return ResourceManager.GetString("WindowActionPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string WindowActionStart {
            get {
                return ResourceManager.GetString("WindowActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string WindowActionStop {
            get {
                return ResourceManager.GetString("WindowActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TipOff 的本地化字符串。
        /// </summary>
        public static string WindowActionTipOff {
            get {
                return ResourceManager.GetString("WindowActionTipOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TipOn 的本地化字符串。
        /// </summary>
        public static string WindowActionTipOn {
            get {
                return ResourceManager.GetString("WindowActionTipOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UV 的本地化字符串。
        /// </summary>
        public static string WindowActionUV {
            get {
                return ResourceManager.GetString("WindowActionUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait 的本地化字符串。
        /// </summary>
        public static string WindowActionWait {
            get {
                return ResourceManager.GetString("WindowActionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Board position layout (4×3) 的本地化字符串。
        /// </summary>
        public static string WindowBoardPosition {
            get {
                return ResourceManager.GetString("WindowBoardPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumables Warehouse 的本地化字符串。
        /// </summary>
        public static string WindowConsumablesWarehouse {
            get {
                return ResourceManager.GetString("WindowConsumablesWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string WindowLoginCancel {
            get {
                return ResourceManager.GetString("WindowLoginCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        public static string WindowLoginOK {
            get {
                return ResourceManager.GetString("WindowLoginOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string WindowLoginPass {
            get {
                return ResourceManager.GetString("WindowLoginPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your password. 的本地化字符串。
        /// </summary>
        public static string WindowLoginPassTitle {
            get {
                return ResourceManager.GetString("WindowLoginPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string WindowLoginUser {
            get {
                return ResourceManager.GetString("WindowLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your username. 的本地化字符串。
        /// </summary>
        public static string WindowLoginUserTitle {
            get {
                return ResourceManager.GetString("WindowLoginUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LogOut 的本地化字符串。
        /// </summary>
        public static string WindowLogOut {
            get {
                return ResourceManager.GetString("WindowLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string WindowOneclickdeletion {
            get {
                return ResourceManager.GetString("WindowOneclickdeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process List 的本地化字符串。
        /// </summary>
        public static string WindowProcessList {
            get {
                return ResourceManager.GetString("WindowProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build 的本地化字符串。
        /// </summary>
        public static string Windowrapidgenerating {
            get {
                return ResourceManager.GetString("Windowrapidgenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step details 的本地化字符串。
        /// </summary>
        public static string WindowStepdetails {
            get {
                return ResourceManager.GetString("WindowStepdetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the process steps to view details. 的本地化字符串。
        /// </summary>
        public static string WindowStepdetails2 {
            get {
                return ResourceManager.GetString("WindowStepdetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8-Channel Pipetting Workstation 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current User: 的本地化字符串。
        /// </summary>
        public static string WindowUser {
            get {
                return ResourceManager.GetString("WindowUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string WindowUserName {
            get {
                return ResourceManager.GetString("WindowUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 1.0.0 的本地化字符串。
        /// </summary>
        public static string WindowVersion {
            get {
                return ResourceManager.GetString("WindowVersion", resourceCulture);
            }
        }
    }
}
